"""add price bars table

Revision ID: 5137b044b175
Revises: f053322a7337
Create Date: 2026-08-02 16:42:40.233759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5137b044b175'
down_revision: Union[str, Sequence[str], None] = 'f053322a7337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=32), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'timestamp', 'timeframe', 'source', name='uq_price_bars_ticker_timestamp_timeframe_source')
    )
    op.create_index(op.f('ix_price_bars_id'), 'price_bars', ['id'], unique=False)
    op.create_index(op.f('ix_price_bars_ticker'), 'price_bars', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_bars_timeframe'), 'price_bars', ['timeframe'], unique=False)
    op.create_index(op.f('ix_price_bars_timestamp'), 'price_bars', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_bars_timestamp'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_timeframe'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_ticker'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_id'), table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
