"""add pipeline tables and raw document metadata

Revision ID: 6ce378bfbf92
Revises: 5137b044b175
Create Date: 2026-08-13 03:11:17.479489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce378bfbf92'
down_revision: Union[str, Sequence[str], None] = '5137b044b175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_id'), 'model_runs', ['id'], unique=False)
    op.create_index(op.f('ix_model_runs_model_name'), 'model_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_runs_model_version'), 'model_runs', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_runs_status'), 'model_runs', ['status'], unique=False)
    op.create_index(op.f('ix_model_runs_ticker'), 'model_runs', ['ticker'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=128), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('params_json', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_runs_id'), 'source_runs', ['id'], unique=False)
    op.create_index(op.f('ix_source_runs_source_type'), 'source_runs', ['source_type'], unique=False)
    op.create_index(op.f('ix_source_runs_status'), 'source_runs', ['status'], unique=False)
    op.create_index(op.f('ix_source_runs_ticker'), 'source_runs', ['ticker'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('horizon', sa.String(length=32), nullable=False),
    sa.Column('prediction_label', sa.String(length=32), nullable=False),
    sa.Column('prediction_probability', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=32), nullable=True),
    sa.Column('uncertainty_level', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_horizon'), 'predictions', ['horizon'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_label'), 'predictions', ['prediction_label'], unique=False)
    op.create_index(op.f('ix_predictions_ticker'), 'predictions', ['ticker'], unique=False)
    op.create_table('training_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_type', sa.String(length=128), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=True),
    sa.Column('sentiment', sa.String(length=32), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('previous_1d_return', sa.Float(), nullable=True),
    sa.Column('previous_5d_return', sa.Float(), nullable=True),
    sa.Column('return_1d', sa.Float(), nullable=True),
    sa.Column('return_3d', sa.Float(), nullable=True),
    sa.Column('abnormal_return_1d', sa.Float(), nullable=True),
    sa.Column('label_1d', sa.String(length=32), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['market_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_examples_event_time'), 'training_examples', ['event_time'], unique=False)
    op.create_index(op.f('ix_training_examples_event_type'), 'training_examples', ['event_type'], unique=False)
    op.create_index(op.f('ix_training_examples_id'), 'training_examples', ['id'], unique=False)
    op.create_index(op.f('ix_training_examples_label_1d'), 'training_examples', ['label_1d'], unique=False)
    op.create_index(op.f('ix_training_examples_sentiment'), 'training_examples', ['sentiment'], unique=False)
    op.create_index(op.f('ix_training_examples_source_type'), 'training_examples', ['source_type'], unique=False)
    op.create_index(op.f('ix_training_examples_ticker'), 'training_examples', ['ticker'], unique=False)
    op.add_column('raw_documents', sa.Column('external_id', sa.String(length=512), nullable=True))
    op.add_column('raw_documents', sa.Column('query', sa.Text(), nullable=True))
    op.add_column('raw_documents', sa.Column('ticker_context', sa.String(length=16), nullable=True))
    op.add_column('raw_documents', sa.Column('company_context', sa.String(length=255), nullable=True))
    op.add_column('raw_documents', sa.Column('raw_payload_json', sa.JSON(), nullable=True))
    op.add_column('raw_documents', sa.Column('processing_status', sa.String(length=32), server_default='new', nullable=False))
    op.add_column('raw_documents', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_raw_documents_external_id'), 'raw_documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_documents_processing_status'), 'raw_documents', ['processing_status'], unique=False)
    op.create_index(op.f('ix_raw_documents_ticker_context'), 'raw_documents', ['ticker_context'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_documents_ticker_context'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_processing_status'), table_name='raw_documents')
    op.drop_index(op.f('ix_raw_documents_external_id'), table_name='raw_documents')
    op.drop_column('raw_documents', 'processed_at')
    op.drop_column('raw_documents', 'processing_status')
    op.drop_column('raw_documents', 'raw_payload_json')
    op.drop_column('raw_documents', 'company_context')
    op.drop_column('raw_documents', 'ticker_context')
    op.drop_column('raw_documents', 'query')
    op.drop_column('raw_documents', 'external_id')
    op.drop_index(op.f('ix_training_examples_ticker'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_source_type'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_sentiment'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_label_1d'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_id'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_event_type'), table_name='training_examples')
    op.drop_index(op.f('ix_training_examples_event_time'), table_name='training_examples')
    op.drop_table('training_examples')
    op.drop_index(op.f('ix_predictions_ticker'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_label'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_horizon'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_source_runs_ticker'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_status'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_source_type'), table_name='source_runs')
    op.drop_index(op.f('ix_source_runs_id'), table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index(op.f('ix_model_runs_ticker'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_status'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model_version'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_model_name'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_id'), table_name='model_runs')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
